### PR TITLE
Added Israeli flag

### PR DESCRIPTION
**Pull request by hillai**

### CODE REVIEW

**Comment by ManrajGrover** [comment]
@hillai Hey! Thank you for contributing! :smile: This looks great! But we already have PR #32 for this. 

I'll keep this open and if other maintainer stops responding, I'll merge this.

**Comment by hillai** [comment]
Oh :( Haven't noticed. I think mine looks closer to the [original](https://en.wikipedia.org/wiki/File:Flag_of_Israel.svg) but sure. Cheers!

**Comment by hillai** [comment]
So... what's up with that other PR? Doesn't really seem active :sweat_smile:

**Comment by ManrajGrover** [comment]
@hillai Can you resolve merge conflicts so we can land this? :smile:

**Pull request closed without merging**
