### PR TITLE
Add Iran Flag

### PR DESCRIPTION
**Pull request by shahinism**
I've added Iran flag :)

cool project btw :+1:

### CODE REVIEW

**Comment by ManrajGrover** [comment]
@shahinism Hey! :smile: 

This is great! Good work! I just checked and found this does not look same as [Flag of Iran](https://en.wikipedia.org/wiki/Flag_of_Iran) on Wikipedia. Please check and comment.

**Comment by shahinism** [comment]
Thanks,
If you mean the `Allahu Akbar` part, yes it is different :) BTW, this is the closest look I can implement without using of inline svg (They are not allowed right?):

selection_159


What do you think?

**Comment by ManrajGrover** [comment]
@shahinism Yeps, no svgs. You can still use `:after` pseudo element and `content` property in it for this. It would be great if this works out well. :smile: 

Let me know if you make progress in it. Even I'll try to do the same. :smile:

**Comment by shahinism** [comment]
Sure, thanks for the tips :+1:

**Pull request closed without merging**
