### PR TITLE
Union Jack

### PR DESCRIPTION
**Pull request by jdhoek**
Flag of the United Kingdom.

It's a national holiday here in the Netherlands, and I kept wondering if there was another interesting flag to tackle. This one took a bit of trigonometry to solve. :gb:

### CODE REVIEW

**Comment by ManrajGrover** [comment]
Rebase this one too please.

**Comment by jdhoek** [comment]
These conflicts happen because the README.md gets out of sync after each merge.

**Comment by ManrajGrover** [comment]
Yeah. :) Great work though! :)

**Comment by ManrajGrover** [comment]
@jdhoek,

Do you have good ideas that can be explored other than ones mentioned? :blush:

**Comment by jdhoek** [comment]
@ManrajGrover

Perhaps demonstrate the basic shapes that can be achieved with just one div and CSS; such as arrows.

**Pull request merged**
