### PR TITLE
Add box loader

### PR DESCRIPTION
**Pull request by AnubrataDS**
A simple box-shaped loader :) 
( Also , this is my first PR on GitHub ! )

### CODE REVIEW

**Comment by ManrajGrover** [comment]
@AnubrataDS Awesome work! :smile: Can you also update README.md as per [Contributions](https://github.com/ManrajGrover/SingleDivProject/blob/master/CONTRIBUTIONS.md) guidelines

**Comment by AnubrataDS** [comment]
sure thing ! I'm on it :)

**Comment by AnubrataDS** [comment]
I updated it

**Comment by ManrajGrover** [comment]
@AnubrataDS Thank you for contributing! :smile: Merged this.

**Pull request merged**
