### PR TITLE
Added Indian flag

### PR DESCRIPTION
**Pull request by fadilf**

### CODE REVIEW

**Comment by fadilf** [comment]
Should I remove the Chinese flag from the commit?

**Comment by ManrajGrover** [comment]
@fadilf Hey! Thank you for contributing! :smile: All of these look great. We already have PR #37 for flag of People's Republic of China. Can you please send individual PRs for each of the flags. It would be easy to maintain and merge for me. :smile:

**Comment by fadilf** [comment]
@ManrajGrover I edited the pull request to be just the Indian flag.

**Comment by ManrajGrover** [comment]
@fadilf Awesome work! :smile: Merging this. You may send individual PRs for all flags.

Keep contributing :smile:

**Pull request merged**
