### PR TITLE
Flag of the United States of America

### PR DESCRIPTION
**Pull request by jdhoek**
I had to make it bigger in order for the stars to render properly, so you may want to classify this one as unconventional or experimental.

Because of the use of a glyph (U+2605 BLACK STAR) this flag may not look
right on every operating system. This is how it looks for me:

usa

### CODE REVIEW

**Comment by jdhoek** [comment]
Still awesome that it is possible though. :us:

**Comment by ManrajGrover** [comment]
Hey! :) This branch has merge conflicts. Can you rebase it?

**Comment by jdhoek** [comment]
Done.

**Comment by ManrajGrover** [comment]
Thank you! :blush:

**Pull request merged**
