### PR TITLE
Add Poland flag

### PR DESCRIPTION
**Pull request by mschweichler**
Added flag of Poland

poland

### CODE REVIEW

**Comment by ManrajGrover** [comment]
@mschweichler Hey! 

I just checked and found colors of Poland's flag are white and red. [Source](https://en.wikipedia.org/wiki/Flag_of_Poland). Could you please check and let me know if this is correct?

**Comment by mschweichler** [comment]
Well, yeah, it's true, we can say it's white and red, but official shades are #E9E8E7 white and #D4213D red :)
You can take a look at wikipedia's html to see hex values of colors used in the table.

flag-of-poland

**Comment by mschweichler** [comment]
Ok, I changed colors to  #FFF and #F00 - not official shades, but more popular for sure :)

**Comment by ManrajGrover** [comment]
@mschweichler If its official then yes, we should use it. :)

**Comment by mschweichler** [comment]
@ManrajGrover  done :)

**Comment by ManrajGrover** [comment]
Thank you @mschweichler :smile: Awesome work! Keep contributing!

**Pull request merged**
