### PR TITLE
Add Polish flag

### PR DESCRIPTION
**Pull request by kretusmaximus**

### CODE REVIEW

**Comment by module17** [comment]
Missing Assets and no update to README.md

**Comment by kretusmaximus** [comment]
Apologies - code updated to be compliant with contribution requirements.

poland

**Comment by ManrajGrover** [comment]
@module17 Thank you for reviewing this. :smile: 

@kretusmaximus We have already received a Pull Request for Polish flag. Please check #36 . I'll keep this one open. If maintainer doesn't respond within 14 days, we will review this one. :blush: 

Till then, you can explore more and contribute! :smile:

**Comment by ManrajGrover** [comment]
@kretusmaximus We have merged #36, so this is a duplicate. I'm closing this but keep contributing! :smile:

**Pull request closed without merging**
